#!/bin/bash

ls -al ~/.ssh #lists all existing keys, if any
ssh-keygen -t rsa -b 4096 -C "vikmokut@gmail.com" #generates key
ls -al ~/.ssh
eval "$(ssh-agent -s)" #initiates ssh agent
ssh-add ~/.ssh/id_rsa #Adds ssh key to agent
clip < ~/.ssh/id_rsa.pub #cpy key to clipboard
ssh -T git@github.com #test connection

#once this scripts runs successfull, paste key on github